language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
      fast_finish: true

cache: cargo

script:
  - |
    cargo build &&
    cargo test &&
    cargo rustdoc -- --document-private-items

after_success:
  - bash .travis.deploy.sh
